allowBuilds:
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: true
  unrs-resolver: true

overrides:
  effect: "^3.20.0"
  deepmerge-ts: "^8.0.0"
  mysql2: "^3.23.1"
  qs: "^6.16.0"